#note: copy this file to the parent directory of this folder in order to execute 'docker-compose up'

version: '3'

services:
  connector:
    build: ./telegram-connector
    environment:
      - TOKEN=1052831284:AAFhNUColiG4mn0q57qyvePH19M8JsVtMwM
    networks:
      connector-distributor-network:
        aliases:
            - connector

  distributor:
    build: ./distributionservice
    ports:
      - 8080:8080
    depends_on:
      - connector
      - postgres
    networks:
      connector-distributor-network:
        aliases:
          - distributor
      distributor-private-network:
        aliases:
          - distributor
      nordbahn-service-network:
        aliases:
          - distributor
      translate-service-network:
        aliases:
          - distributor
      urlshortener-service-network:
        aliases:
          - distributor
      wikipedia-service-network:
        aliases:
          - distributor
      weather-service-network:
        aliases:
          - distributor

  postgres:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - DEBUG=false
      - DB_NAME=telegram
      - DB_USER=telegram
      - DB_PASS=telegram
    volumes:
      - /srv/docker/postgresql:/var/lib/postgresql
    networks:
      distributor-private-network:
        aliases:
          - postgres

  nordbahn:
    build: ./nordbahnservice
    depends_on:
      - distributor
    networks:
      nordbahn-service-network:
        aliases:
          - nordbahn

  translate:
    build: ./translateservice
    depends_on:
      - distributor
    networks:
      translate-service-network:
        aliases:
          - translate

  urlshortener:
    build: ./urlshortenerservice
    depends_on:
      - distributor
    networks:
      urlshortener-service-network:
        aliases:
          - urlshortener

  wikipedia:
    build: ./wikipediaservice
    depends_on:
      - distributor
    networks:
      wikipedia-service-network:
        aliases:
          - wikipedia

  weather:
    build: ./weatherservice
    depends_on:
      - distributor
      - mariadb
    networks:
      weather-service-network:
        aliases:
          - weather
      weather-private-network:
        aliases:
          - weather

  mariadb:
    image: bitnami/mariadb:latest
    restart: on-failure
    environment:
      - MARIADB_ROOT_USER=telegram-weather
      - MARIADB_ROOT_PASSWORD=fqWSU9Y7mLDmLTpKDA84fFg3rGEem8yAdNy57C2gcJJMjT7e9C3wEzpCzR5juZy6
      - MARIADB_DATABASE=telegram-weather
    networks:
      weather-private-network:
        aliases:
          - mariadb

networks:
  connector-distributor-network:
    driver: bridge
  distributor-private-network:
    driver: bridge
  nordbahn-service-network:
    driver: bridge
  translate-service-network:
    driver: bridge
  urlshortener-service-network:
    driver: bridge
  wikipedia-service-network:
    driver: bridge
  weather-service-network:
    driver: bridge
  weather-private-network:
    driver: bridge